### ISSUE TITLE
请问如何卸载呢？

### ISSUE THREAD

**Issue by takff** [helloxz/nginx-cdn#1]
怎么搜不到安装路径和进程，但打开网页又看到Nginx字样？

**Comment by helloxz** [comment]
1. 安装路径在`/usr/local/nginx`
2. `ps -ef|grep 'nginx'`看下是否有进程
3. 再次执行脚本`sh nginx.sh` 根据提示进行卸载

**Comment by takff** [comment]
Thanks

**Comment by helloxz** [comment]
不客气
