### ISSUE TITLE
centos7使用二进制安装后没法用

### ISSUE THREAD

**Issue by wojiaopanhaoran** [helloxz/nginx-cdn#3]
centos7使用二进制安装后nginx -V无显示 之前还是好使的，是不是这次更新的时候大佬有疏漏啊

**Comment by helloxz** [comment]
`nginx -V`有报错吗，访问IP能看到安装成功的页面吗？

**Comment by wojiaopanhaoran** [comment]
重建了一台vps安装，centos7.6，二进制安装完毕后nginx -V提示：-bash: nginx: 未找到命令。执行source /etc/profile后再执行nginx -v，提示nginx: error while loading shared libraries: libjemalloc.so.2: cannot open shared object file: No such file or directory。大佬是不是修改路径了

**Comment by wojiaopanhaoran** [comment]
编译安装，nginx-v正常，显示如下
nginx version: xcdn/1.18.0
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --user=www --group=www --with-stream=dynamic --with-http_stub_status_module --with-http_v2_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module --with-http_slice_module --with-http_image_filter_module=dynamic --with-pcre=../pcre-8.43 --with-pcre-jit --with-zlib=../zlib-1.2.11 --with-openssl=../openssl-1.1.1g --add-module=../ngx_cache_purge --add-module=../ngx_brotli --add-dynamic-module=/usr/local/testcookie-nginx-module --add-dynamic-module=/usr/local/ngx_http_geoip2_module

不过似乎没有stream，转发还要自己再搞一下，能加在一起就好了

**Comment by helloxz** [comment]
其实有stream，不过改用动态加载了，空了我更新下文档。二进制的我先测试下。

**Comment by helloxz** [comment]
二进制文件已重新打包，现已可用。`stream`已改用动态模块，后续更新文档。

**Comment by wojiaopanhaoran** [comment]
大佬辛苦
